### ISSUE TITLE
java jar filename is inconsistent

### ISSUE THREAD

**Issue by patmarion** [RobotLocomotion/lcmtypes#10]
the lcmtypes jar file is named `robotlocomotion-lcmtypes.jar` but by convention lcmtypes jar files are of the style `lcmtypes_<package>.jar` as in `lcmtypes_drake.jar`.

This causes a problem because the bot-spy script only looks for jar files named `lcmtypes_*.jar`.

**Comment by patmarion** [comment]
it might be as simple as fixing this line:

https://github.com/RobotLocomotion/lcmtypes/blob/master/lcmtypes/CMakeLists.txt#L78

**Comment by patmarion** [comment]
@manuelli

**Comment by manuelli** [comment]
resolved by #11
