### ISSUE TITLE
Tagging for Drake

### ISSUE THREAD

**Issue by TheCynosure** [RobotLocomotion/lcmtypes#15]
The v0.31 release of drake uses the most recent commit (821ff4b463a9cb8f616914d87289714fcb356a92) on this repository. Could you possibly tag that commit? I would like to use this code but need it to be tagged before I can do that.

**Comment by jwnimmer-tri** [comment]
Done at https://github.com/RobotLocomotion/lcmtypes/releases/tag/v0.0.20170613.

Note that Drake's use of `RobotLocomotion/lcmtypes` was deprecated as of https://drake.mit.edu/release_notes/v0.29.0.html and removed as of https://drake.mit.edu/release_notes/v0.33.0.html, so this should be moot for most users.
