### ISSUE TITLE
Is build system up to date?

### ISSUE THREAD

**Issue by patmarion** [RobotLocomotion/lcmtypes#5]
Are the CMakeLists.txt in this repo exactly up to date with the latest and greatest version that is used elsewhere (like bot-core-lcmtypes)?  I tried to do a build and got a link error.  Even though the CMakeLIsts.txt has this line:

```
target_link_libraries(robotlocomotion-lcmtypes PUBLIC INTERFACE lcmtypes_bot2-core)
```

It did not add that library to the link line during make.  Has anyone tested this repo yet?

**Comment by david-german-tri** [comment]
@mwoehlke-kitware

**Comment by sammy-tri** [comment]
I believe it will only build inside the Drake superbuild right now, as the superbuild provides the bot2-core dependency.

**Comment by patmarion** [comment]
I had provided the bot2-core package from openhumanoids.  It didn't actually have trouble finding the package, but linking against it at build time.

**Comment by wxmerkt** [comment]
@patmarion Are you using the bot2-core master or legacy line? OH hasn't switched to the newly merged master yet (I am maintaining both branches simultaneously) as it requires a broken CMake'ified LCM and is not backwards compatible with the legacy LCM. I'd actually like to make either the legacy LCM compatible with the new lcmtypes build system or to have LCM fixed

**Comment by patmarion** [comment]
using openhumanoids/bot_core_lcmtypes master branch, and lcm master branch.

**Comment by wxmerkt** [comment]
Okay that should work otherwise this is something to be fixed. Does bot-spy work for you using the lcm master branch?

**Comment by patmarion** [comment]
Unfortunately I don't know how to quickly debug this link error.  I suspect it has to do with the target_link_libraries(... PUBLIC INTERFACE ...) stuff.  I'm not that familiar with the new interface stuff cmake supports.

**Comment by mwoehlke-kitware** [comment]
`target_link_libraries(... PUBLIC INTERFACE ...)` looks wrong... the `PUBLIC` with no libraries listed is superfluous. Maybe it should just be `PUBLIC` (no `INTERFACE`)?

Note:
- `PRIVATE`: Building the library needs to link to listed libraries. Consumers don't need to link listed libraries.
- `PUBLIC`: Listed libraries need to be linked both when building the library and when the library is consumed.
- `INTERFACE`: Listed libraries are needed when the library is consumed, but _not_ when it is built.

(...and of course `PRIVATE` → `PUBLIC` if the library in question is static.)

Probably related: the line `include_directories($<TARGET_PROPERTY:lcmtypes_bot2-core,INTERFACE_INCLUDE_DIRECTORIES>)` should not be needed. (In fact, please avoid use of `include_directories`.)

**Comment by mwoehlke-kitware** [comment]
I think this patch is wanted:

``` diff
diff --git a/lcmtypes/CMakeLists.txt b/lcmtypes/CMakeLists.txt
index e01c2cb..4c93daa 100644
--- a/lcmtypes/CMakeLists.txt
+++ b/lcmtypes/CMakeLists.txt
@@ -31,19 +31,17 @@ lcm_wrap_types(
   support_sequence_t.lcm
   )

-include_directories($<TARGET_PROPERTY:lcmtypes_bot2-core,INTERFACE_INCLUDE_DIRECTORIES>)
-
 lcm_add_library(robotlocomotion-lcmtypes C ${c_sources} ${c_install_headers})
 generate_export_header(robotlocomotion-lcmtypes
   BASE_NAME robotlocomotion_lcmtypes)
 target_include_directories(robotlocomotion-lcmtypes INTERFACE
   $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>)
-target_link_libraries(robotlocomotion-lcmtypes PUBLIC INTERFACE lcmtypes_bot2-core)
+target_link_libraries(robotlocomotion-lcmtypes PUBLIC lcmtypes_bot2-core)

 lcm_add_library(robotlocomotion-lcmtypes-cpp CPP ${cpp_install_headers})
 target_include_directories(robotlocomotion-lcmtypes-cpp INTERFACE
   $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>)
-target_link_libraries(robotlocomotion-lcmtypes-cpp PUBLIC INTERFACE lcmtypes_bot2-core-cpp)
+target_link_libraries(robotlocomotion-lcmtypes-cpp PUBLIC lcmtypes_bot2-core-cpp)

 lcm_install_headers(
   ${c_install_headers}
```

**Comment by patmarion** [comment]
Yep, that patch fixed it, except for the last line.  It says:

CMake Error at lcmtypes/CMakeLists.txt:46 (target_link_libraries):
  INTERFACE library can only be used with the INTERFACE keyword of
  target_link_libraries

This is more stuff that is new to me (I'll try to catch up :) ).  lcmtypes_bot2-core-cpp isn't a physical library, but just a target in cmake?  And it's only defined as an interface?

**Comment by patmarion** [comment]
But without modifying the last line, then it compiles and links.  Only issue was that I had to manually copy the export header on the bot_core_lcmtypes project, I opened an issue there:

https://github.com/openhumanoids/bot_core_lcmtypes/issues/27

Let me know if you want to look at that one, or else I can try myself.  Thanks @mwoehlke-kitware

**Comment by mwoehlke-kitware** [comment]
Ah, right... C should be `PUBLIC`, C++ should be `INTERFACE` (the C++ library isn't actually "built", it's just an artifact used to convey usage requirements, and sometimes dependencies).

**Comment by mwoehlke-kitware** [comment]
I added a comment to openhumanoids/bot_core_lcmtypes#27 with the necessary (trivial) patch. This repo has the same issue and also needs a similar fix.

(Since I am not feeling well ATM, if you can PR these, that would be appreciated; either way I'll try to take a look before the weekend.)

**Comment by patmarion** [comment]
I'll take care of it.  Thanks for stopping in!  Feel better.

**Comment by patmarion** [comment]
resolved by PR.
